# Generated by Django 2.2.10 on 2021-02-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210206_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
