# Generated by Django 2.2.10 on 2021-02-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20210206_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('present_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_present', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Volunteer_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contributer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Contributer_Profile')),
                ('event_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
