# Generated by Django 2.2.10 on 2021-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_volunteer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
